name: Jarvis Build Cloud
on:
  push:
    branches: [ "master", "main" ]

env:
  # Ép toàn bộ các Actions chạy trên môi trường Node.js 24 theo yêu cầu của sếp
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Hiện tại GitHub hỗ trợ tối đa bản 20/22 ổn định, nhưng biến môi trường trên sẽ kích hoạt nhân Node 24 bên dưới

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          cd jarvis_mobile
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Build APK
        run: |
          cd jarvis_mobile
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: jarvis-app-release
          path: jarvis_mobile/build/app/outputs/flutter-apk/app-release.apk
